export const GET_HOSPITALS = 'GET_HOSPITALS';
export const GET_HOSPITALS_SUCCESS = 'GET_HOSPITALS_SUCCESS';
export const GET_HOSPITALS_ERROR = 'GET_HOSPITALS_ERROR';
//
export const SET_HOSPITAL_ERROR = 'SET_HOSPITAL_ERROR';
//
export const SELECT_HOSPITAL = 'SELECT_HOSPITAL';
// export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SELECT_DOCTOR = 'SELECT_DOCTOR';
export const SELECT_DAY = 'SELECT_DAY';
export const SELECT_CARD = 'SELECT_CARD';
export const RESET_BOOKING = 'RESET_BOOKING';

export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';

export const GET_DOCTORS = 'GET_DOCTORS';
export const GET_DOCTORS_SUCCESS = 'GET_DOCTORS_SUCCESS';
export const GET_DOCTORS_ERROR = 'GET_DOCTORS_ERROR';

export const BOOK_APPOINTMENT = 'BOOK_APPOINTMENT';
export const BOOK_APPOINTMENT_SUCCESS = 'BOOK_APPOINTMENT_SUCCESS';
export const BOOK_APPOINTMENT_ERROR = 'BOOK_APPOINTMENT_ERROR';

export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';
export const GET_APPOINTMENTS_ERROR = 'GET_APPOINTMENTS_ERROR';
