
/////////////////   OLD TYPES    /////////////////
export const GET_NAMES = 'GET_NAMES';
export const GET_NAMES_SUCCESS = 'GET_NAMES_SUCCESS';
export const GET_NAMES_ERROR = 'GET_NAMES_ERROR';

export const GET_TRENDING_NAMES = 'GET_TRENDING_NAMES';
export const GET_TRENDING_NAMES_SUCCESS = 'GET_TRENDING_NAMES_SUCCESS';
export const GET_TRENDING_NAMES_ERROR = 'GET_TRENDING_NAMES_ERROR';

export const GET_WORLD_TRENDING_NAMES = 'GET_WORLD_TRENDING_NAMES';
export const GET_WORLD_TRENDING_NAMES_SUCCESS =
  'GET_WORLD_TRENDING_NAMES_SUCCESS';
export const GET_WORLD_TRENDING_NAMES_ERROR = 'GET_WORLD_TRENDING_NAMES_ERROR';

export const GET_RELATED_NAMES = 'GET_RELATED_NAMES';
export const GET_RELATED_NAMES_SUCCESS = 'GET_RELATED_NAMES_SUCCESS';
export const GET_RELATED_NAMES_ERROR = 'GET_RELATED_NAMES_ERROR';
export const CLEAR_RELATED_NAMES = 'CLEAR_RELATED_NAMES';

export const SET_DETAIL_ITEM = 'SET_DETAIL_ITEM';

export const SET_GENDER = 'SET_GENDER';
export const CLEAR_GENDER = 'CLEAR_GENDER';

export const SET_RELIGION = 'SET_RELIGION';
export const CLEAR_RELIGION = 'CLEAR_RELIGION';

export const SET_KEYWORD = 'SET_KEYWORD';
export const CLEAR_KEYWORD = 'CLEAR_KEYWORD';

export const SET_ORIGIN = 'SET_ORIGIN';

export const SET_ALPHABET = 'SET_ALPHABET';

export const SET_LOADING = 'SET_LOADING';

export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE';

export const VISITED_ALL_NAMES = 'VISITED_ALL_NAMES';
export const RESET = 'RESET';

export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';

export const GET_ALL_ORIGINS = 'GET_ALL_ORIGINS';
export const GET_ALL_ORIGINS_SUCCESS = 'GET_ALL_ORIGINS_SUCCESS';
export const GET_ALL_ORIGINS_ERROR = 'GET_ALL_ORIGINS_ERROR';

export const GET_BLOGS = 'GET_BLOGS';
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const GET_BLOGS_ERROR = 'GET_BLOGS_ERROR';
